import Foundation

enum AppText {
    static let activityEmpty = "No activity recorded yet."
    static let activityThinking = "Thinking"
    static let activityTitle = "Agent Activity"
    static let approve = "Approve"
    static let autoReconnect = "Auto-reconnect"
    static let autoReconnectErrorBody = "The server may be offline or unreachable.\nCheck that it's running and you're on the same network."
    static let autoReconnectErrorTitle = "Could not reach the saved server"
    static let basicAuth = "Basic Auth"
    static let branch = "Branch"
    static let cancel = "Cancel"
    static let connect = "Connect"
    static let connecting = "Connecting..."
    static let connectingSubtitle = "Establishing connection to the server"
    static let connectionSection = "Connection"
    static let copyCode = "Copy Code"
    static let create = "Create"
    static let customAnswer = "Type your own answer"
    static let customPlaceholder = "Type your answer..."
    static let delete = "Delete"
    static let deleteSessionMessage = "This will permanently delete the session and all its messages."
    static let deleteSession = "Delete Session"
    static let deny = "Deny"
    static let dismiss = "Dismiss"
    static let disconnect = "Disconnect"
    static let disconnectMessage = "Disconnect from the OpenCode server? You can reconnect later."
    static let done = "Done"
    static let editBeforeConnecting = "Edit before connecting"
    static let emptyModelsSubtitle = "No connected providers with models were found."
    static let emptyModelsTitle = "No Models Available"
    static let emptySessionsSubtitle = "Create a session to start chatting with OpenCode."
    static let emptySessionsTitle = "No Sessions"
    static let files = "Files"
    static let forget = "Forget"
    static let forgetConnection = "Forget Connection"
    static let forgetConnectionMessage = "Remove this server's credentials from Keychain? You'll need to re-enter them to connect again."
    static let forgetThisConnection = "Forget This Connection"
    static let help = "Help"
    static let loadingModels = "Loading models..."
    static let manualConnection = "Manual Connection"
    static let manualConnectErrorBody = "Check the server address and make sure the server is running."
    static let manualConnectErrorTitle = "Could not connect to server"
    static let messagePlaceholder = "Ask anything or use /command"
    static let model = "Model"
    static let multipleSelection = "Select multiple options"
    static let nearby = "Nearby"
    static let newSession = "New Session"
    static let newSessionMessage = "Create a new chat session."
    static let newSessionPlaceholder = "Title (optional)"
    static let noProviders = "No providers available"
    static let noServersFound = "No servers found. Start OpenCode with --mdns flag."
    static let none = "None"
    static let openCodeServer = "OpenCode Server"
    static let optional = "Optional"
    static let pass = "Pass"
    static let permissionFallback = "The agent is requesting permission to proceed."
    static let permissionRequired = "Permission Required"
    static let project = "Project"
    static let providerModel = "Provider & Model"
    static let providerSubtitle = "Current AI provider configuration"
    static let qrInstruction = "Point camera at QR code"
    static let qrInstructionSubtitle = "Generated by openlens-qr on your computer"
    static let qrInvalid = "Invalid QR code — use openlens-qr to generate"
    static let qrScan = "Scan QR Code"
    static let qrScanSubtitle = "Quick connect via openlens-qr CLI"
    static let reasoning = "Reasoning"
    static let reconnecting = "Reconnecting..."
    static let reconnectingSubtitle = "Reconnecting to your saved server"
    static let refreshProviders = "Refresh Providers"
    static let saved = "Saved"
    static let scanPrompt = "Tap to scan for nearby servers"
    static let searchingServers = "Searching for servers..."
    static let server = "Server"
    static let serverCheckBody = "To connect OpenLens to your computer, you need to have OpenCode running with the server enabled."
    static let serverCheckNo = "No, help me set it up"
    static let serverCheckNoSubtitle = "Step-by-step installation guide"
    static let serverCheckTitle = "Is OpenCode running?"
    static let serverCheckYes = "Yes, it's running"
    static let serverCheckYesSubtitle = "Choose how to connect"
    static let sessions = "Sessions"
    static let settings = "Settings"
    static let settingsForgetDialogTitle = "Forget Connection"
    static let showContextStatus = "Shows context status"
    static let startServer = "Start the server"
    static let statusConnected = "Connected"
    static let statusConnecting = "Connecting..."
    static let statusDisconnected = "Disconnected"
    static let statusError = "Error"
    static let statusOffline = "Offline"
    static let statusReconnecting = "Reconnecting..."
    static let submit = "Submit"
    static let switchAction = "Switch"
    static let switchMessage = "You are currently connected. Disconnect and connect to the new server?"
    static let switchServerTitle = "Switch Server?"
    static let tryDebugChat = "Open Debug Chat"
    static let tryDebugChatSubtitle = "Replay a heavy streaming scenario for chat comparison"
    static let thinking = "Thinking"
    static let thinkingDefault = "Default"
    static let titleUntitled = "Untitled"
    static let tools = "Tools"
    static let tryAgain = "Try Again"
    static let tryDemo = "Try Demo"
    static let tryDemoSubtitle = "See how it works without a server"
    static let url = "URL"
    static let user = "User"
    static let version = "Version"
    static let working = "Working..."
    static let wizardConnectBody = "Choose the quickest way to connect your iPhone to the OpenCode server."
    static let wizardConnectBonjour = "Auto-detect on network"
    static let wizardConnectBonjourSubtitle = "Requires --mdns flag on server"
    static let wizardConnectManual = "Enter address manually"
    static let wizardConnectManualSubtitle = "Type the IP address shown in terminal"
    static let wizardConnectQR = "Scan QR Code"
    static let wizardConnectQRSubtitle = "Fastest — no typing needed"
    static let wizardConnectQRTipTitle = "Generate a QR Code"
    static let wizardConnectTitle = "How to connect?"
    static let wizardInstallBody = "On your computer, open a terminal and run:"
    static let wizardInstallHint = "Your iPhone and computer must be on the same Wi-Fi network. The --hostname 0.0.0.0 flag exposes the server on all network interfaces."
    static let wizardInstallReady = "Server is running, continue"
    static let wizardInstallRunBody = "Navigate to your project folder and start OpenCode with the server exposed on your network:"
    static let wizardInstallRunTitle = "Start the server"
    static let wizardInstallTitle = "Install OpenCode"

    static let onboardingPageQRTitle = "Quick Connect with QR"
    static let onboardingPageQRBody = """
    The fastest way to connect is scanning a QR code generated by the `openlens-qr` tool included in this repo.

    **1.** Open Terminal in the project root.

    **2.** Build the CLI tool once:
    `xcrun swift build -c release --package-path Tools/openlens-qr`

    **3.** Start the QR flow:
    `Tools/openlens-qr/.build/release/openlens-qr --serve`

    The server starts first, then the QR code appears in your terminal. Scan it with OpenLens before pressing Enter to open the TUI.
    """
    static let onboardingPageQRHint = """
    `--serve` starts OpenCode, waits until the server is reachable, prints the QR code, and only opens the TUI after you confirm with Enter.
    If you set `OPENLENS_QR_PASSWORD=secret`, the same secret is applied to the server, encoded in the QR deep link, and reused when the TUI attaches.
    By default the printed deep link is masked. Use `--print-secret-link` only when you explicitly want to reveal the full link in the terminal.
    """
    static let onboardingPage1Title = "Start manually"
    static let onboardingPage1Body = """
    If you want to start OpenCode manually instead of using the QR helper, run:
    **opencode serve --port 4096 --hostname 0.0.0.0**

    This exposes the server on your local network so OpenLens can reach it from your iPhone. Keep your iPhone and Mac on the same Wi-Fi.
    """
    static let onboardingPage1Hint = """
    Recommended default: use `openlens-qr --serve` from this repo when you want QR setup and a local TUI in one flow.
    Don't have OpenCode? `curl -fsSL https://opencode.ai/install | bash`
    """
    static let onboardingPage2Title = "Connect"
    static let onboardingPage2Body = """
    Make sure your iPhone and Mac are on the **same Wi-Fi network**.
    **Fastest: QR Code**
    From the project root run `cd Tools/openlens-qr`, build once with `xcrun swift build -c release`, then run `.build/release/openlens-qr --serve`.
    The tool starts the server first, shows a QR code while it is already live, and waits for you to scan before opening the TUI.
    **Manual** — enter the IP address, e.g. `192.168.1.50:4096`.
    """
    static let onboardingPage2Hint = """
    Useful variants:
    `OPENLENS_QR_PASSWORD=secret openlens-qr --serve`
    `OPENLENS_QR_PASSWORD=secret openlens-qr 192.168.1.50:4096`
    `OPENLENS_QR_PASSWORD=secret openlens-qr --print-secret-link`

    `OPENLENS_QR_PASSWORD` secures the server in serve mode and includes the same secret in the QR deep link, so OpenLens can connect without retyping it.
    Build from the repo root with: `xcrun swift build -c release --package-path Tools/openlens-qr`
    """
    static let onboardingPage3Title = "One session, many places"
    static let onboardingPage3Body = """
    OpenCode works like a server — you can have the **TUI in a terminal**, a browser, and OpenLens open at the same time, all connected to the same session.
    Changes and messages sync in real time.
    """
    static let onboardingPage3Hint = "With `openlens-qr --serve`, press Enter after scanning to open the TUI while keeping the same server available to your phone."
    static let onboardingPage4Title = "Attach to a server"
    static let onboardingPage4Body = """
    If the server is already running (e.g. via `opencode serve` or `opencode web`), you can attach a terminal to it without restarting:
    **opencode attach http://192.168.1.50:4096**

    The TUI will connect to the existing instance — sessions and history are preserved.
    """
    static let onboardingPage4Hint = "Useful when the server is running remotely or in the background. You can also attach with a specific session: `opencode attach http://host:4096 --session <id>`"
    static let onboardingNext = "Next"
    static let onboardingStart = "Let's go"

    static let wizardConnectQRTipBody = "On your computer, run this command to start the server and include the secret from `OPENLENS_QR_PASSWORD` in the QR flow. The TUI opens only after you scan and press Enter:"

    static func activitySteps(_ count: Int) -> String {
        "Steps (\(count))"
    }

    static func contextUsageLabel(_ usagePercent: Int, usedTokens: Int, limitTokens: Int) -> String {
        "Context usage \(usagePercent) percent, \(usedTokens) of \(limitTokens) tokens used"
    }

    static func contextUsageLabel(_ usedTokens: Int) -> String {
        "Context usage, \(usedTokens) tokens used"
    }

    static func markdownShowMore(_ remainingCount: Int) -> String {
        "Show more (\(remainingCount) blocks)"
    }

    static func onboardingStep(_ current: Int, _ total: Int) -> String {
        "Step \(current) of \(total)"
    }
}
